model:
  name: d_loc_test
  path: models/OD_models/d_loc_weights.pt
  tau: 0.5
data:
  dataset: d_loc_test
  start: 0
  end: 10
  std: [1.]
  mean: [0.]
  test_csv: models/OD_models/d_loc_test_2.csv
  num_outputs: 1
specification:
  epsilon: 0.01
  norm: .inf
  robustness_type: OD_IoU
attack:
  pgd_restarts: 2
solver:
  batch_size: 2
  beta-crown:
    iteration: 10
bab:
  timeout: 180
